#pragma once

#using <mscorlib.dll>
#using <System.dll>
#using <System.Xml.dll>
#using <System.Web.Services.dll>
#using <System.EnterpriseServices.dll>

using namespace System::Security::Permissions;
[assembly:SecurityPermissionAttribute(SecurityAction::RequestMinimum, SkipVerification=false)];
// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace com_microsofttranslatorapi1 {
    using namespace System::Xml::Serialization;
    using namespace System::Web::Services;
    using namespace System::ComponentModel;
    using namespace System::Web::Services::Protocols;
    using namespace System;
    using namespace System::Diagnostics;
    using namespace System;
    ref class Soap;
    ref class GetLanguagesCompletedEventArgs;
    ref class GetLanguageNamesCompletedEventArgs;
    ref class DetectCompletedEventArgs;
    ref class TranslateCompletedEventArgs;
    
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038")]
    public delegate System::Void GetLanguagesCompletedEventHandler(System::Object^  sender, com_microsofttranslatorapi1::GetLanguagesCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038")]
    public delegate System::Void GetLanguageNamesCompletedEventHandler(System::Object^  sender, com_microsofttranslatorapi1::GetLanguageNamesCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038")]
    public delegate System::Void DetectCompletedEventHandler(System::Object^  sender, com_microsofttranslatorapi1::DetectCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038")]
    public delegate System::Void TranslateCompletedEventHandler(System::Object^  sender, com_microsofttranslatorapi1::TranslateCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Web::Services::WebServiceBindingAttribute(Name=L"BasicHttpBinding_LanguageService", Namespace=L"http://api.microsofttranslator.com/v1/soap.svc")]
    public ref class Soap : public System::Web::Services::Protocols::SoapHttpClientProtocol {
        
        private: System::Threading::SendOrPostCallback^  GetLanguagesOperationCompleted;
        
        private: System::Threading::SendOrPostCallback^  GetLanguageNamesOperationCompleted;
        
        private: System::Threading::SendOrPostCallback^  DetectOperationCompleted;
        
        private: System::Threading::SendOrPostCallback^  TranslateOperationCompleted;
        
        /// <remarks/>
        public: event com_microsofttranslatorapi1::GetLanguagesCompletedEventHandler^  GetLanguagesCompleted;
        
        /// <remarks/>
        public: event com_microsofttranslatorapi1::GetLanguageNamesCompletedEventHandler^  GetLanguageNamesCompleted;
        
        /// <remarks/>
        public: event com_microsofttranslatorapi1::DetectCompletedEventHandler^  DetectCompleted;
        
        /// <remarks/>
        public: event com_microsofttranslatorapi1::TranslateCompletedEventHandler^  TranslateCompleted;
        
        /// <remarks/>
        public: Soap();
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"http://api.microsofttranslator.com/v1/soap.svc/LanguageService/GetLanguages", 
            RequestNamespace=L"http://api.microsofttranslator.com/v1/soap.svc", ResponseNamespace=L"http://api.microsofttranslator.com/v1/soap.svc", 
            Use=System::Web::Services::Description::SoapBindingUse::Literal, ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        [returnvalue: System::Xml::Serialization::XmlArrayAttribute(IsNullable=true)]
        [returnvalue: System::Xml::Serialization::XmlArrayItemAttribute(Namespace=L"http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        cli::array< System::String^  >^  GetLanguages([System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] 
                    System::String^  appId);
        
        /// <remarks/>
        public: System::IAsyncResult^  BeginGetLanguages(System::String^  appId, System::AsyncCallback^  callback, System::Object^  asyncState);
        
        /// <remarks/>
        public: cli::array< System::String^  >^  EndGetLanguages(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void GetLanguagesAsync(System::String^  appId);
        
        /// <remarks/>
        public: System::Void GetLanguagesAsync(System::String^  appId, System::Object^  userState);
        
        private: System::Void OnGetLanguagesOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"http://api.microsofttranslator.com/v1/soap.svc/LanguageService/GetLanguageNames", 
            RequestNamespace=L"http://api.microsofttranslator.com/v1/soap.svc", ResponseNamespace=L"http://api.microsofttranslator.com/v1/soap.svc", 
            Use=System::Web::Services::Description::SoapBindingUse::Literal, ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        [returnvalue: System::Xml::Serialization::XmlArrayAttribute(IsNullable=true)]
        [returnvalue: System::Xml::Serialization::XmlArrayItemAttribute(Namespace=L"http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        cli::array< System::String^  >^  GetLanguageNames([System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] 
                    System::String^  appId, [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] System::String^  locale);
        
        /// <remarks/>
        public: System::IAsyncResult^  BeginGetLanguageNames(System::String^  appId, System::String^  locale, System::AsyncCallback^  callback, 
                    System::Object^  asyncState);
        
        /// <remarks/>
        public: cli::array< System::String^  >^  EndGetLanguageNames(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void GetLanguageNamesAsync(System::String^  appId, System::String^  locale);
        
        /// <remarks/>
        public: System::Void GetLanguageNamesAsync(System::String^  appId, System::String^  locale, System::Object^  userState);
        
        private: System::Void OnGetLanguageNamesOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"http://api.microsofttranslator.com/v1/soap.svc/LanguageService/Detect", 
            RequestNamespace=L"http://api.microsofttranslator.com/v1/soap.svc", ResponseNamespace=L"http://api.microsofttranslator.com/v1/soap.svc", 
            Use=System::Web::Services::Description::SoapBindingUse::Literal, ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        [returnvalue: System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        System::String^  Detect([System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] System::String^  appId, 
                    [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] System::String^  text);
        
        /// <remarks/>
        public: System::IAsyncResult^  BeginDetect(System::String^  appId, System::String^  text, System::AsyncCallback^  callback, 
                    System::Object^  asyncState);
        
        /// <remarks/>
        public: System::String^  EndDetect(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void DetectAsync(System::String^  appId, System::String^  text);
        
        /// <remarks/>
        public: System::Void DetectAsync(System::String^  appId, System::String^  text, System::Object^  userState);
        
        private: System::Void OnDetectOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"http://api.microsofttranslator.com/v1/soap.svc/LanguageService/Translate", 
            RequestNamespace=L"http://api.microsofttranslator.com/v1/soap.svc", ResponseNamespace=L"http://api.microsofttranslator.com/v1/soap.svc", 
            Use=System::Web::Services::Description::SoapBindingUse::Literal, ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        [returnvalue: System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        System::String^  Translate([System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] System::String^  appId, 
                    [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] System::String^  text, [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] 
                    System::String^  from, [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] System::String^  to);
        
        /// <remarks/>
        public: System::IAsyncResult^  BeginTranslate(
                    System::String^  appId, 
                    System::String^  text, 
                    System::String^  from, 
                    System::String^  to, 
                    System::AsyncCallback^  callback, 
                    System::Object^  asyncState);
        
        /// <remarks/>
        public: System::String^  EndTranslate(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void TranslateAsync(System::String^  appId, System::String^  text, System::String^  from, System::String^  to);
        
        /// <remarks/>
        public: System::Void TranslateAsync(System::String^  appId, System::String^  text, System::String^  from, System::String^  to, 
                    System::Object^  userState);
        
        private: System::Void OnTranslateOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: System::Void CancelAsync(System::Object^  userState) new;
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class GetLanguagesCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: GetLanguagesCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                    System::Boolean cancelled, System::Object^  userState);
        /// <remarks/>
        public: property cli::array< System::String^  >^  Result {
            cli::array< System::String^  >^  get();
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class GetLanguageNamesCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: GetLanguageNamesCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                    System::Boolean cancelled, System::Object^  userState);
        /// <remarks/>
        public: property cli::array< System::String^  >^  Result {
            cli::array< System::String^  >^  get();
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class DetectCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: DetectCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, System::Boolean cancelled, 
                    System::Object^  userState);
        /// <remarks/>
        public: property System::String^  Result {
            System::String^  get();
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class TranslateCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: TranslateCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, System::Boolean cancelled, 
                    System::Object^  userState);
        /// <remarks/>
        public: property System::String^  Result {
            System::String^  get();
        }
    };
}
namespace com_microsofttranslatorapi1 {
    
    
    inline Soap::Soap() {
        this->Url = L"http://api.microsofttranslator.com/v1/Soap.svc";
    }
    
    inline cli::array< System::String^  >^  Soap::GetLanguages([System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] 
                System::String^  appId) {
        cli::array< System::Object^  >^  results = this->Invoke(L"GetLanguages", gcnew cli::array< System::Object^  >(1) {appId});
        return (cli::safe_cast<cli::array< System::String^  >^  >(results[0]));
    }
    
    inline System::IAsyncResult^  Soap::BeginGetLanguages(System::String^  appId, System::AsyncCallback^  callback, System::Object^  asyncState) {
        return this->BeginInvoke(L"GetLanguages", gcnew cli::array< System::Object^  >(1) {appId}, callback, asyncState);
    }
    
    inline cli::array< System::String^  >^  Soap::EndGetLanguages(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (cli::safe_cast<cli::array< System::String^  >^  >(results[0]));
    }
    
    inline System::Void Soap::GetLanguagesAsync(System::String^  appId) {
        this->GetLanguagesAsync(appId, nullptr);
    }
    
    inline System::Void Soap::GetLanguagesAsync(System::String^  appId, System::Object^  userState) {
        if (this->GetLanguagesOperationCompleted == nullptr) {
            this->GetLanguagesOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &com_microsofttranslatorapi1::Soap::OnGetLanguagesOperationCompleted);
        }
        this->InvokeAsync(L"GetLanguages", gcnew cli::array< System::Object^  >(1) {appId}, this->GetLanguagesOperationCompleted, 
            userState);
    }
    
    inline System::Void Soap::OnGetLanguagesOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->GetLanguagesCompleted(this, (gcnew com_microsofttranslatorapi1::GetLanguagesCompletedEventArgs(invokeArgs->Results, 
                    invokeArgs->Error, invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline cli::array< System::String^  >^  Soap::GetLanguageNames([System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] 
                System::String^  appId, [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] System::String^  locale) {
        cli::array< System::Object^  >^  results = this->Invoke(L"GetLanguageNames", gcnew cli::array< System::Object^  >(2) {appId, 
                locale});
        return (cli::safe_cast<cli::array< System::String^  >^  >(results[0]));
    }
    
    inline System::IAsyncResult^  Soap::BeginGetLanguageNames(System::String^  appId, System::String^  locale, System::AsyncCallback^  callback, 
                System::Object^  asyncState) {
        return this->BeginInvoke(L"GetLanguageNames", gcnew cli::array< System::Object^  >(2) {appId, locale}, callback, asyncState);
    }
    
    inline cli::array< System::String^  >^  Soap::EndGetLanguageNames(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (cli::safe_cast<cli::array< System::String^  >^  >(results[0]));
    }
    
    inline System::Void Soap::GetLanguageNamesAsync(System::String^  appId, System::String^  locale) {
        this->GetLanguageNamesAsync(appId, locale, nullptr);
    }
    
    inline System::Void Soap::GetLanguageNamesAsync(System::String^  appId, System::String^  locale, System::Object^  userState) {
        if (this->GetLanguageNamesOperationCompleted == nullptr) {
            this->GetLanguageNamesOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &com_microsofttranslatorapi1::Soap::OnGetLanguageNamesOperationCompleted);
        }
        this->InvokeAsync(L"GetLanguageNames", gcnew cli::array< System::Object^  >(2) {appId, locale}, this->GetLanguageNamesOperationCompleted, 
            userState);
    }
    
    inline System::Void Soap::OnGetLanguageNamesOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->GetLanguageNamesCompleted(this, (gcnew com_microsofttranslatorapi1::GetLanguageNamesCompletedEventArgs(invokeArgs->Results, 
                    invokeArgs->Error, invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline System::String^  Soap::Detect([System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] System::String^  appId, 
                [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] System::String^  text) {
        cli::array< System::Object^  >^  results = this->Invoke(L"Detect", gcnew cli::array< System::Object^  >(2) {appId, 
                text});
        return (cli::safe_cast<System::String^  >(results[0]));
    }
    
    inline System::IAsyncResult^  Soap::BeginDetect(System::String^  appId, System::String^  text, System::AsyncCallback^  callback, 
                System::Object^  asyncState) {
        return this->BeginInvoke(L"Detect", gcnew cli::array< System::Object^  >(2) {appId, text}, callback, asyncState);
    }
    
    inline System::String^  Soap::EndDetect(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (cli::safe_cast<System::String^  >(results[0]));
    }
    
    inline System::Void Soap::DetectAsync(System::String^  appId, System::String^  text) {
        this->DetectAsync(appId, text, nullptr);
    }
    
    inline System::Void Soap::DetectAsync(System::String^  appId, System::String^  text, System::Object^  userState) {
        if (this->DetectOperationCompleted == nullptr) {
            this->DetectOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &com_microsofttranslatorapi1::Soap::OnDetectOperationCompleted);
        }
        this->InvokeAsync(L"Detect", gcnew cli::array< System::Object^  >(2) {appId, text}, this->DetectOperationCompleted, userState);
    }
    
    inline System::Void Soap::OnDetectOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->DetectCompleted(this, (gcnew com_microsofttranslatorapi1::DetectCompletedEventArgs(invokeArgs->Results, invokeArgs->Error, 
                    invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline System::String^  Soap::Translate([System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] System::String^  appId, 
                [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] System::String^  text, [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] 
                System::String^  from, [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] System::String^  to) {
        cli::array< System::Object^  >^  results = this->Invoke(L"Translate", gcnew cli::array< System::Object^  >(4) {appId, 
                text, from, to});
        return (cli::safe_cast<System::String^  >(results[0]));
    }
    
    inline System::IAsyncResult^  Soap::BeginTranslate(
                System::String^  appId, 
                System::String^  text, 
                System::String^  from, 
                System::String^  to, 
                System::AsyncCallback^  callback, 
                System::Object^  asyncState) {
        return this->BeginInvoke(L"Translate", gcnew cli::array< System::Object^  >(4) {appId, text, from, to}, callback, asyncState);
    }
    
    inline System::String^  Soap::EndTranslate(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (cli::safe_cast<System::String^  >(results[0]));
    }
    
    inline System::Void Soap::TranslateAsync(System::String^  appId, System::String^  text, System::String^  from, System::String^  to) {
        this->TranslateAsync(appId, text, from, to, nullptr);
    }
    
    inline System::Void Soap::TranslateAsync(System::String^  appId, System::String^  text, System::String^  from, System::String^  to, 
                System::Object^  userState) {
        if (this->TranslateOperationCompleted == nullptr) {
            this->TranslateOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &com_microsofttranslatorapi1::Soap::OnTranslateOperationCompleted);
        }
        this->InvokeAsync(L"Translate", gcnew cli::array< System::Object^  >(4) {appId, text, from, to}, this->TranslateOperationCompleted, 
            userState);
    }
    
    inline System::Void Soap::OnTranslateOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->TranslateCompleted(this, (gcnew com_microsofttranslatorapi1::TranslateCompletedEventArgs(invokeArgs->Results, 
                    invokeArgs->Error, invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline System::Void Soap::CancelAsync(System::Object^  userState) {
        __super::CancelAsync(userState);
    }
    
    
    inline GetLanguagesCompletedEventArgs::GetLanguagesCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline cli::array< System::String^  >^  GetLanguagesCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (cli::safe_cast<cli::array< System::String^  >^  >(this->results[0]));
    }
    
    
    inline GetLanguageNamesCompletedEventArgs::GetLanguageNamesCompletedEventArgs(cli::array< System::Object^  >^  results, 
                System::Exception^  exception, System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline cli::array< System::String^  >^  GetLanguageNamesCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (cli::safe_cast<cli::array< System::String^  >^  >(this->results[0]));
    }
    
    
    inline DetectCompletedEventArgs::DetectCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline System::String^  DetectCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (cli::safe_cast<System::String^  >(this->results[0]));
    }
    
    
    inline TranslateCompletedEventArgs::TranslateCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline System::String^  TranslateCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (cli::safe_cast<System::String^  >(this->results[0]));
    }
}
